<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
    <Compile Remove="Main.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="NewFile1.txt" />
    <None Remove="U25small.txt" />
    <None Remove="U_50small.txt" />
    <None Remove="V_25sma" />
  </ItemGroup>

  <ItemGroup>
    <None Update="U_25medium.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="U_50large.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
